### ISSUE TITLE
lightgbm no longer works

### ISSUE THREAD

**Issue by pinogl** [curso-r/treesnip#38]
Hi,
Unfortunately, `lightgbm `stopped working on my machine.
I tried to run the code of your vignette `working-with-lightgbm-catboost.Rmd` and the call to `fit_resamples` raised a fatal error and the R session crashed without any further information. 
The `catboost` example run fine.
Please find attached my session info.

Thanks

` package     * version    date       lib source                           
 AmesHousing   0.0.4      2020-06-23 [1] CRAN (R 4.0.1)                   
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                   
 backports     1.2.1      2020-12-09 [1] CRAN (R 4.0.3)                   
 bitops        1.0-6      2013-08-17 [1] CRAN (R 4.0.0)                   
 boot          1.3-27     2021-02-12 [2] CRAN (R 4.0.4)                   
 broom       * 0.7.5      2021-02-19 [1] CRAN (R 4.0.4)                   
 cachem        1.0.4      2021-02-13 [1] CRAN (R 4.0.3)                   
 callr         3.6.0      2021-03-28 [1] CRAN (R 4.0.4)                   
 caTools       1.18.2     2021-03-28 [1] CRAN (R 4.0.4)                   
 class         7.3-18     2021-01-24 [2] CRAN (R 4.0.4)                   
 cli           2.3.1      2021-02-23 [1] CRAN (R 4.0.4)                   
 codetools     0.2-18     2020-11-04 [2] CRAN (R 4.0.4)                   
 colorspace    2.0-0      2020-11-11 [1] CRAN (R 4.0.3)                   
 corrr         0.4.3      2020-11-24 [1] CRAN (R 4.0.3)                   
 crayon        1.4.1      2021-02-08 [1] CRAN (R 4.0.3)                   
 DBI           1.1.1      2021-01-15 [1] CRAN (R 4.0.3)                   
 debugme       1.1.0      2017-10-22 [1] CRAN (R 4.0.0)                   
 desc          1.3.0      2021-03-05 [1] CRAN (R 4.0.4)                   
 descriptr     0.5.2      2020-12-09 [1] CRAN (R 4.0.3)                   
 DescTools     0.99.40    2021-02-03 [1] CRAN (R 4.0.3)                   
 devtools      2.3.2      2020-09-18 [1] CRAN (R 4.0.2)                   
 dials       * 0.0.9      2020-09-16 [1] CRAN (R 4.0.2)                   
 DiceDesign    1.9        2021-02-13 [1] CRAN (R 4.0.3)                   
 digest        0.6.27     2020-10-24 [1] CRAN (R 4.0.3)                   
 dplyr       * 1.0.5      2021-03-05 [1] CRAN (R 4.0.4)                   
 e1071         1.7-6      2021-03-18 [1] CRAN (R 4.0.4)                   
 ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.0)                   
 Exact         2.1        2020-10-02 [1] CRAN (R 4.0.2)                   
 expm          0.999-6    2021-01-13 [1] CRAN (R 4.0.3)                   
 extrafont     0.17       2014-12-08 [1] CRAN (R 4.0.0)                   
 extrafontdb   1.0        2012-06-11 [1] CRAN (R 4.0.0)                   
 fansi         0.4.2      2021-01-15 [1] CRAN (R 4.0.3)                   
 fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.0.3)                   
 foreach       1.5.1      2020-10-15 [1] CRAN (R 4.0.3)                   
 fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                   
 furrr         0.2.2      2021-01-29 [1] CRAN (R 4.0.3)                   
 future        1.21.0     2020-12-10 [1] CRAN (R 4.0.3)                   
 generics      0.1.0      2020-10-31 [1] CRAN (R 4.0.3)                   
 ggplot2     * 3.3.3      2020-12-30 [1] CRAN (R 4.0.3)                   
 ggpmisc       0.3.9      2021-04-04 [1] CRAN (R 4.0.4)                   
 gld           2.6.2      2020-01-08 [1] CRAN (R 4.0.2)                   
 glmnet        4.1-1      2021-02-21 [1] CRAN (R 4.0.4)                   
 globals       0.14.0     2020-11-22 [1] CRAN (R 4.0.3)                   
 glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                   
 gower         0.2.2      2020-06-23 [1] CRAN (R 4.0.1)                   
 GPfit         1.0-8      2019-02-08 [1] CRAN (R 4.0.0)                   
 gtable        0.3.0      2019-03-25 [1] CRAN (R 4.0.0)                   
 infer       * 0.5.4      2021-01-13 [1] CRAN (R 4.0.3)                   
 ipred         0.9-11     2021-03-12 [1] CRAN (R 4.0.4)                   
 iterators     1.0.13     2020-10-15 [1] CRAN (R 4.0.3)                   
 janitor       2.1.0      2021-01-05 [1] CRAN (R 4.0.3)                   
 lattice       0.20-41    2020-04-02 [2] CRAN (R 4.0.4)                   
 lava          1.6.9      2021-03-11 [1] CRAN (R 4.0.4)                   
 lhs           1.1.1      2020-10-05 [1] CRAN (R 4.0.2)                   
 lifecycle     1.0.0      2021-02-15 [1] CRAN (R 4.0.3)                   
 lime          0.5.2      2021-02-24 [1] CRAN (R 4.0.4)                   
 listenv       0.8.0      2019-12-05 [1] CRAN (R 4.0.0)                   
 lmom          2.8        2019-03-12 [1] CRAN (R 4.0.0)                   
 lubridate     1.7.10     2021-02-26 [1] CRAN (R 4.0.4)                   
 magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.0.3)                   
 MASS          7.3-53.1   2021-02-12 [1] CRAN (R 4.0.3)                   
 Matrix        1.3-2      2021-01-06 [2] CRAN (R 4.0.4)                   
 memoise       2.0.0      2021-01-26 [1] CRAN (R 4.0.3)                   
 modeldata   * 0.1.0      2020-10-22 [1] CRAN (R 4.0.3)                   
 munsell       0.5.0      2018-06-12 [1] CRAN (R 4.0.0)                   
 mvtnorm       1.1-1      2020-06-09 [1] CRAN (R 4.0.0)                   
 nnet          7.3-15     2021-01-24 [2] CRAN (R 4.0.4)                   
 pacman        0.5.1      2019-03-11 [1] CRAN (R 4.0.0)                   
 parallelly    1.24.0     2021-03-14 [1] CRAN (R 4.0.4)                   
 parsnip     * 0.1.5      2021-01-19 [1] CRAN (R 4.0.3)                   
 pillar        1.5.1      2021-03-05 [1] CRAN (R 4.0.4)                   
 pkgbuild      1.2.0      2020-12-15 [1] CRAN (R 4.0.3)                   
 pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.0)                   
 pkgload       1.2.0      2021-02-23 [1] CRAN (R 4.0.4)                   
 plyr          1.8.6      2020-03-03 [1] CRAN (R 4.0.0)                   
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.0)                   
 pROC          1.17.0.1   2021-01-13 [1] CRAN (R 4.0.3)                   
 processx      3.5.1      2021-04-04 [1] CRAN (R 4.0.4)                   
 prodlim       2019.11.13 2019-11-17 [1] CRAN (R 4.0.0)                   
 proxy         0.4-25     2021-03-05 [1] CRAN (R 4.0.4)                   
 ps            1.6.0      2021-02-28 [1] CRAN (R 4.0.4)                   
 purrr       * 0.3.4      2020-04-17 [1] CRAN (R 4.0.0)                   
 R6            2.5.0      2020-10-28 [1] CRAN (R 4.0.3)                   
 Rcpp          1.0.6      2021-01-15 [1] CRAN (R 4.0.3)                   
 recipes     * 0.1.15     2020-11-11 [1] CRAN (R 4.0.3)                   
 remotes       2.3.0      2021-04-01 [1] CRAN (R 4.0.4)                   
 rlang         0.4.10     2020-12-30 [1] CRAN (R 4.0.3)                   
 rootSolve     1.8.2.1    2020-04-27 [1] CRAN (R 4.0.0)                   
 rpart         4.1-15     2019-04-12 [2] CRAN (R 4.0.4)                   
 rprojroot     2.0.2      2020-11-15 [1] CRAN (R 4.0.3)                   
 rsample     * 0.0.9      2021-02-17 [1] CRAN (R 4.0.4)                   
 rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.0.3)                   
 Rttf2pt1      1.3.8      2020-01-10 [1] CRAN (R 4.0.0)                   
 scales      * 1.1.1      2020-05-11 [1] CRAN (R 4.0.0)                   
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.0)                   
 shape         1.4.5      2020-09-13 [1] CRAN (R 4.0.2)                   
 snakecase     0.11.0     2019-05-25 [1] CRAN (R 4.0.0)                   
 stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)                   
 stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.0)                   
 survival      3.2-7      2020-09-28 [2] CRAN (R 4.0.4)                   
 testthat      3.0.2      2021-02-14 [1] CRAN (R 4.0.3)                   
 tibble      * 3.1.0      2021-02-25 [1] CRAN (R 4.0.4)                   
 tidymodels  * 0.1.2      2020-11-22 [1] CRAN (R 4.0.3)                   
 tidyr       * 1.1.3      2021-03-03 [1] CRAN (R 4.0.4)                   
 tidyselect    1.1.0      2020-05-11 [1] CRAN (R 4.0.0)                   
 timeDate      3043.102   2018-02-21 [1] CRAN (R 4.0.0)                   
 treesnip    * 0.1.0.9000 2021-01-20 [1] Github (curso-r/treesnip@bf27cd8)
 tune        * 0.1.3      2021-02-28 [1] CRAN (R 4.0.4)                   
 usethis       2.0.1      2021-02-10 [1] CRAN (R 4.0.3)                   
 utf8          1.2.1      2021-03-12 [1] CRAN (R 4.0.4)                   
 vctrs         0.3.7      2021-03-29 [1] CRAN (R 4.0.4)                   
 withr         2.4.1      2021-01-26 [1] CRAN (R 4.0.3)                   
 workflows   * 0.2.2      2021-03-10 [1] CRAN (R 4.0.4)                   
 yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)                   
 yardstick   * 0.0.8      2021-03-28 [1] CRAN (R 4.0.4)  `

**Comment by issactoast** [comment]
maybe you need to update other dependecies. mine works okay except the `categorical_features`

**Comment by pinogl** [comment]
It seems to be an issue of the current version of lightgbm on windows machines.
[[R-package] FATAL Error when run train()](https://github.com/microsoft/LightGBM/issues/4045)
It should be fixed with the next ligthgbm release.
