### ISSUE TITLE
lightGbm still crashing on Win 10

### ISSUE THREAD

**Issue by Steviey** [curso-r/treesnip#47]
_Win10, R 4.x, all libs. latest_

I still can reproduce this:

https://gitmemory.com/issue/microsoft/LightGBM/4007/784502902

on my system.

![image](https://user-images.githubusercontent.com/3146082/128644227-cc96e4c9-54ce-41e3-907e-9ce5067bfb3a.png)

It also crashes wtih:

```
if (require("lightgbm")) {
  library(AmesHousing)
  # data cleaning
  library(janitor)
  # data prep
  #library(dplyr)
  # visualisation
  library(ggplot2)
  library(yardstick)
  library(catboost)
  library(tidymodels)
  library(treesnip)
  library(tidyverse)

}
```

**Comment by dfalbel** [comment]
This is related to: https://github.com/microsoft/LightGBM/issues/4464
You can see this comment for a workaround: https://github.com/microsoft/LightGBM/issues/4464#issuecomment-890454199
