### ISSUE TITLE
This is an awesome package! can I help?

### ISSUE THREAD

**Issue by RMHogervorst** [curso-r/treesnip#5]
I just modified a tutorial example based on xgboost and with only replacing the engine from
"xgboost" to "lightgbm" it just works! Amazing work!

How can I help?

**Comment by Athospd** [comment]
@RMHogervorst would be awesome! Well, we are at a very early stage. 

I just found out that lightgbm is not working with tune() (badly, it causes R to crash). you can check it out here https://github.com/curso-r/treesnip/blob/master/tests/testthat/test-lightgbm.R

Also I think we need a lot of unit tests! 

If we set a good battery of successful tests we can start spreading the word about this pkg.

**Comment by Athospd** [comment]
Just an update: lightgbm + tune is crashing is a windows specific issue. Mac and Linux are not crashing.

**Comment by RMHogervorst** [comment]
Cool, yeah lightgbm worked without a hitch on my mac, but catboost had some issues.
