### ISSUE TITLE
Is catboost support deprecated ?

### ISSUE THREAD

**Issue by sametsoekel** [curso-r/treesnip#67]
When I freshly install `treesnip`, `show_engines('boost_tree')` doesn't show `catboost` as an engine.  Similarly a specification like;

```
boost_tree() %>%
set_mode('classification') %>%
set_engine('catboost')
```

also says that `catboost` is not supported when `treesnip` is attached.

**Comment by EmilHvitfeldt** [comment]
Hello @sametsoekel 👋 

As [per the readme](https://github.com/curso-r/treesnip#catboost):

> Originally treesnip had support for both lightgbm and catboost. Since catboost has no intent to make it to CRAN we removed the parsnip implementation from the main package. You can still use it from the catboost branch that we will keep up to date with the main branch.

The catboost branch can be installed with:

```r
remotes::install_github("curso-r/treesnip@catboost")
```
