### ISSUE TITLE
categorical vars

### ISSUE THREAD

**Issue by dfalbel** [curso-r/treesnip#7]
Both catboost and lightgbm advantages are the built-in support of categorical variables.
Figure out and document how to correctly pass them.

**Comment by RMHogervorst** [comment]
So I've used lightgbm with python extensively in the last year and with pandas you can manually specify which columns are categorical. In R data.frames I think it would be nice if character and factor would automatically be selected, unless you manually specify it. Let me dive in the lightgbm R docs for more info

**Comment by RMHogervorst** [comment]
lightgbm docs [say](https://github.com/microsoft/LightGBM/blob/master/R-package/demo/categorical_features_prepare.R#L62)

> The categorical features must be indexed like in R (1-indexed, not 0-indexed)

So column number.

**Comment by RMHogervorst** [comment]
catboost also uses column indices, but 0 indexed according to [their docs](https://catboost.ai/docs/concepts/r-reference_catboost-load_pool.html). 
> A vector of categorical features indices.

> The indices are zero-based and can differ from the ones given in the columns description file.

**Comment by dfalbel** [comment]
I agree with consider factors/strings columns as categorical variables. My main concern is how we should deal with new levels in the categorical features or if this is already handled by catboost and lightgbm.

**Comment by dfalbel** [comment]
We will probably need to change how we deal with cat vars here:

https://github.com/curso-r/treesnip/blob/master/R/lightgbm.R#L180

And also change the itnerface here: https://github.com/curso-r/treesnip/blob/master/R/lightgbm.R#L16 to data.frame as IIUC is `matrix` means only numeric.

**Comment by RMHogervorst** [comment]
As far as I can see, catboost does not allow you to specify the categorical features in the train function, but only in the data loading part. In lightgbm you do have to specify it in the train function and also in the data.

**Comment by RMHogervorst** [comment]
> I agree with consider factors/strings columns as categorical variables. My main concern is how we should deal with new levels in the categorical features or if this is already handled by catboost and lightgbm.

Isn't that more a recipes problem? There is a step_others or something in recipes.

**Comment by RMHogervorst** [comment]
In this more recent commit I don't think you pass the indices of categorical variables to the `train` function of lgbm, only to the `lgb.Dataset`?

**Comment by RMHogervorst** [comment]
No I'm afraid not.

**Comment by RMHogervorst** [comment]
I would test the categorical check and maybe the dataset that it creates. Those are simple to do. Creating a dataset that tests whether categorical variables are used is hella difficult. Because to my understanding both catboost and lightgbm do incredibly sophisticated things to both numeric and categorical features. So even if we create factors that should be separable into groups or something the trees would split those if they were numbers too. Maybe we can check the unittests inside of lightgbm or catboost for examples ?
